## Input Data##

Below data is another text classification, problem, ham and spam detection. A sms you recives in your mobile phone could be eighte ham or spam.

In [1]:
texts = [
    "Pay your connection bill of 2000",
    "Win 20000 by participating in the lottery.",
    "Win 200 rupees by participating this competition at gamer.com.",
    "I will come tomorrow"
]

## Turn each of this sms to it's numerical vector (Bag of Words) ##

In [6]:
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

cv = CountVectorizer(ngram_range=(1,1))
features = cv.fit_transform(texts)
pd.DataFrame(
features.todense(),
columns = cv.get_feature_names())

,200,2000,20000,at,bill,by,com,come,competition,connection,...,of,participating,pay,rupees,the,this,tomorrow,will,win,your
0,0,1,0,0,1,0,0,0,0,1,...,1,0,1,0,0,0,0,0,0,1
1,0,0,1,0,0,1,0,0,0,0,...,0,1,0,0,1,0,0,0,1,0
2,1,0,0,1,0,1,1,0,1,0,...,0,1,0,1,0,1,0,0,1,0
3,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,1,1,0,0